### ISSUE TITLE
Cannot create trigger

### ISSUE THREAD

**Issue by king2** [HuasoFoundries/phpPgAdmin6#216]
While trying to create trigger with PostgreSQL 9.6, an error raises:
**Call to undefined method PHPPgAdmin\Database\Postgres96::getTriggerFunctions() at line 420.**

**Comment by amenadiel** [comment]
I'm sorry I hadn't seen this before.
Regarding the issue, for some reason whose forensics I'll do when I get some spare time, the method was removed while refactoring. 

I restored it so it should be fine by now... but since I never wrote tests for the database methods (only for routes and controllers) we have yet to find out
