### ISSUE TITLE
PostgreSQL 12 Support

### ISSUE THREAD

**Issue by klaxian** [HuasoFoundries/phpPgAdmin6#243]
When attempting to log in to a PostgreSQL 12 server, I get the following error. However, it should work if you remove the artificial version check.

> Version of PostgreSQL not supported. Please upgrade to version 9.3 or later.

**Comment by ffflabs** [comment]
Whoa, you're quite an early adopter. But then again, I appreciate it. 

Just released RC2. Previous version only considered up to PG11. It's not really an artificial version check, because some views, catalogs, classes and other system stuff does change. However I don't think it would be catastrophic if PG13 comes out and the approach to create FTS has changed.

...as long as 80% is usable

**Comment by klaxian** [comment]
Thank you very much! I'm only an early adopter on my development systems so I can find little issues like this. I wouldn't upgrade production until everything is solid. However, it's worth noting that PG12 final was released two months ago and 12.1 is nearly a month old as well. It doesn't seem that early... :p

**Comment by ffflabs** [comment]
Yeah that's true, besides this one was my fault for hardcoding 11. (Still, my fix was hardcode up to 13).

However there's PHP 7.4 issue from yesterday as well. That one wreaked havoc in my dev environment. :laughing:
