### ISSUE TITLE
Same Sequence Shown Multiple Times in Sidebar

### ISSUE THREAD

**Issue by klaxian** [HuasoFoundries/phpPgAdmin6#271]
When expanding the "sequences" list in the sidebar navigation, the same sequence name is repeated throughout the entire list.

**Comment by ffflabs** [comment]
Whoa this one is new. 
Yeah, I can see the backend can't figure out the link for each sequence quite right, therefore it returns an url which lacks the sequence name, so all of them have the same (broken) link. The unique id used to draw the nested tree is computed from these links, so the same ID led to repeated entries.

It's fixed in 6.1.3
