### ISSUE TITLE
Cannot insert new rows

### ISSUE THREAD

**Issue by tingvold** [HuasoFoundries/phpPgAdmin6#346]
Trying to insert new rows, yields the following error;

![image](https://user-images.githubusercontent.com/359918/95861097-4248fb00-0d61-11eb-8824-5563e73d76f5.png)
![image](https://user-images.githubusercontent.com/359918/95861121-4e34bd00-0d61-11eb-8c60-3b2d8b5ec77c.png)

**Comment by ffflabs** [comment]
It's fixed in release v6.1.**1** (the last one is for said bug).

It seems a lot of bugs got introduced after this commit: https://github.com/HuasoFoundries/phpPgAdmin6/commit/2b72a6599564901461c9c537e641b58f9fe8cd62

Basically, several loose comparison operators were replaced with strict equality. For the insertion operation it compares a numeric string sent through $_POST against an incremental record. They would never pass that internal check, and the error message does not help either.

There might be quite a few errors of this same kind. At least I'm pretty sure where to look for the breaking change .
